---DSB ESB---
--[[ Autogenerated by ESB.
 Trying to edit this file by hand may not give you
 particularly good results.
]]

dsb_text2map(0, 20, 16, 100, 0, {
"00000000010000000000",
"00000000010000111001",
"00111011110000101001",
"00101010010111111001",
"00111111010100100000",
"00001001010100100000",
"00001001011110111111",
"01111111010011100001",
"01010010011100111000",
"01110010010100101000",
"00001110011100100000",
"00001011100001110000",
"00001110100111010000",
"01000000111101110000",
"01000000100111000000",
"01000011100000000000"} )
dsb_level_flags(0, 2)
dsb_level_wallset(0, wallset.default)
dsb_text2map(1, 22, 19, 0, 4, {
"0000000000000000000000",
"0000000000000000000000",
"0000000000000000000000",
"0000000000000000000100",
"0000000000000000111100",
"0000000000000000100000",
"0000000000000000100000",
"0000000000000000100100",
"0000000000000000111111",
"0000000000000000111111",
"0000000000000000111111",
"0000000000000000000000",
"0011110000000000000000",
"0011110000000000000000",
"0011110000000000000000",
"0111111000000000000000",
"0011110000000000000000",
"0011110000000000000000",
"0011110000000000000000"} )
dsb_level_flags(1, 2)
dsb_level_wallset(1, wallset.default)
dsb_add_champion(1, "NECRO_01", "port_necro", "NECRO", "", 3760, 1650, 1280, 490, 380, 520, 620, 320, 640, 600, {6,5,6,6,7}, {7,6,7,7,8}, {6,7,5,6,5}, {8,9,6,9,5})
dsb_add_champion(2, "LOR_02", "port_lor", "LOR", "CHAMPION OF GOOD", 3700, 3357, 1100, 400, 640, 640, 580, 440, 340, 540, {9,11,7,2,8}, {6,0,8,5,5}, {7,6,7,8,7}, {6,4,4,8,4})
dsb_add_champion(3, "AROC_03", "port_aroc", "AROC", "", 2700, 2000, 1500, 340, 540, 390, 440, 340, 440, 350, {7,5,4,9,5}, {7,9,8,3,4}, {7,6,7,8,6}, {8,4,10,9,7})
dsb_add_champion(4, "PLAGUE_04", "port_plague", "PLAGUE", "", 4100, 1500, 1600, 400, 320, 330, 660, 340, 640, 640, {8,3,4,3,10}, {6,7,7,3,2}, {8,6,5,9,9}, {6,6,6,6,6})
dsb_add_champion(5, "DETH_05", "port_deth", "DETH", "", 3850, 2450, 770, 350, 560, 650, 330, 310, 580, 560, {8,10,6,5,4}, {8,10,7,0,0}, {5,6,0,6,0}, {6,8,0,0,0})
dsb_add_champion(6, "AIRWING_06", "port_airwing", "AIRWING", "", 3000, 1890, 700, 390, 640, 540, 400, 490, 300, 300, {7,9,7,5,7}, {7,8,7,4,7}, {6,8,3,3,4}, {7,0,9,2,2})
dsb_add_champion(7, "LETA_07", "port_leta", "LETA", "", 2300, 2300, 1400, 440, 320, 300, 760, 540, 300, 300, {6,5,5,6,7}, {7,9,4,5,2}, {8,8,9,8,9}, {7,6,9,7,6})
dsb_add_champion(8, "SKELAR_08", "port_skelar", "SKELAR", "THE SLAYER", 4300, 2700, 480, 340, 680, 600, 380, 300, 610, 590, {8,8,8,8,8}, {8,8,8,8,8}, {6,6,6,6,6}, {7,7,7,7,7})
dsb_add_champion(9, "TALON_09", "port_talon", "TALON", "", 2400, 2022, 850, 400, 350, 580, 360, 300, 370, 300, {7,6,8,7,8}, {7,8,8,5,3}, {6,7,2,5,7}, {7,2,8,8,3})
dsb_add_champion(10, "TUNDA_10", "port_tunda", "TUNDA", "THE SUREFOOTED", 3500, 3050, 1040, 340, 640, 580, 430, 640, 470, 510, {7,9,8,7,6}, {7,6,8,7,8}, {7,8,7,8,7}, {7,6,7,8,8})
dsb_add_champion(11, "LANA_11", "port_lana", "LANA", "", 3200, 2450, 1210, 390, 570, 630, 470, 640, 440, 480, {7,6,8,6,8}, {7,8,6,8,8}, {7,7,8,7,8}, {7,8,8,7,6})
dsb_add_champion(12, "TOADROT_12", "port_toadrot", "TOADROT", "PRINCE OF SKULASH", 2500, 1890, 920, 490, 480, 580, 320, 310, 540, 540, {7,7,2,9,2}, {8,7,8,8,9}, {6,6,7,7,7}, {7,6,6,7,8})
dsb_add_champion(13, "DEMA_13", "port_dema", "DEMA", "CHAMPION OF IISSH", 3200, 2750, 650, 360, 680, 340, 300, 560, 380, 640, {7,5,8,7,8}, {7,4,9,7,5}, {7,9,0,0,0}, {7,6,6,8,9})
dsb_add_champion(14, "VEN_14", "port_ven", "VEN", "HIGH PRIEST OF SSHA", 2070, 1700, 1500, 440, 460, 300, 620, 590, 390, 610, {5,2,7,5,6}, {7,9,7,2,7}, {8,8,8,10,7}, {7,6,6,8,7})
dsb_add_champion(15, "ALGOR_15", "port_algor", "ALGOR", "MARSH HUNTER", 3000, 2500, 800, 400, 640, 410, 340, 460, 520, 580, {8,7,9,3,9}, {8,6,10,8,6}, {6,6,6,6,6}, {6,0,3,5,8})
dsb_add_champion(16, "ITZA_16", "port_itza", "ITZA", "WARLORD OF UXMAL", 3000, 2450, 1630, 400, 580, 510, 540, 540, 480, 460, {8,9,7,10,4}, {7,2,8,7,7}, {6,6,6,8,6}, {7,9,7,7,7})
dsb_add_champion(17, "MANTIA_17", "port_mantia", "MANTIA", "SPELLWEAVER OF KELT", 2000, 2230, 1730, 390, 440, 640, 680, 440, 610, 300, {6,4,7,3,7}, {7,2,9,3,5}, {8,8,7,9,7}, {8,6,9,10,7})
dsb_add_champion(18, "GNATU_18", "port_gnatu", "GNATU", "SPEARWING OF LEEF", 2050, 2610, 1500, 540, 300, 680, 530, 410, 550, 380, {7,3,8,2,9}, {7,8,2,5,8}, {8,9,9,6,7}, {7,3,9,7,7})
dsb_add_champion(19, "STING_19", "port_sting", "STING", "", 3000, 2700, 680, 290, 690, 620, 340, 480, 640, 310, {7,6,7,9,6}, {7,2,8,2,9}, {7,9,0,0,0}, {6,7,5,6,5})
dsb_add_champion(20, "TULA_20", "port_tula", "TULA", "PRINCESS OF UXMAL", 2400, 1450, 1370, 390, 390, 620, 560, 490, 560, 550, {7,6,6,7,8}, {7,9,5,7,7}, {7,8,9,7,6}, {7,6,6,8,8})
dsb_add_champion(21, "SLOGAR_21", "port_slogar", "SLOGAR", "WEBBER OF ARACHNIA", 2500, 2650, 700, 290, 720, 640, 370, 360, 530, 310, {8,4,3,2,10}, {8,8,9,8,7}, {7,4,3,6,9}, {6,4,7,7,4})
dsb_add_champion(22, "PETAL_22", "port_petal", "PETAL", "", 2470, 2500, 1760, 510, 330, 660, 610, 620, 640, 340, {4,0,2,0,6}, {5,6,0,3,6}, {8,8,9,7,8}, {9,4,9,9,10})
dsb_add_champion(23, "BUZZZZZ_23", "port_buzzzzz", "BUZZZZZ", "", 2800, 1630, 1800, 650, 310, 690, 600, 620, 650, 380, {4,2,0,0,6}, {5,7,0,4,6}, {8,7,8,8,9}, {8,8,9,9,9})
dsb_add_champion(24, "KAZAI_24", "port_kazai", "KAZAI", "SHADOW WARRIOR", 3500, 2850, 1210, 490, 540, 710, 640, 510, 540, 490, {7,8,6,5,8}, {9,8,10,10,9}, {6,6,3,6,7}, {6,5,8,6,6})
ch_exvar = {
}
dsb_spawnburst_begin(107)
dsb_spawn(49, "mirror", 0, 15, 0, 2)
dsb_spawn(65, "mirror", 0, 19, 0, 2)
dsb_spawn(17, "mirror", 0, 3, 1, 2)
dsb_spawn(37, "floortext", 0, 9, 2, 4)
dsb_spawn(47, "mirror", 0, 13, 2, 1)
dsb_spawn(60, "mirror", 0, 17, 2, 3)
dsb_spawn(68, "doorframe", 0, 19, 2, 4)
dsb_spawn(69, "door_wood_swindow", 0, 19, 2, 4)
dsb_disable(69)
dsb_spawn(3, "mirror", 0, 1, 3, 1)
dsb_spawn(28, "mirror", 0, 5, 3, 3)
dsb_spawn(70, "stairsdown", 0, 19, 3, 4)
dsb_spawn(52, "mirror", 0, 15, 4, 0)
dsb_spawn(21, "mirror", 0, 3, 5, 0)
dsb_spawn(11, "mirror", 0, 2, 6, 2)
dsb_spawn(53, "fakewall", 0, 15, 6, 4)
dsb_spawn(62, "doorframe", 0, 18, 6, 4)
dsb_spawn(63, "door_portcullis", 0, 18, 6, 4)
dsb_spawn(64, "doorbutton", 0, 18, 6, 4)
dsb_spawn(39, "mirror", 0, 10, 7, 2)
dsb_spawn(71, "stairsdown", 0, 19, 7, 4)
dsb_spawn(1, "mirror", 0, 0, 8, 1)
dsb_spawn(25, "mirror", 0, 4, 8, 3)
dsb_spawn(61, "mirror", 0, 17, 8, 3)
dsb_spawn(35, "mirror", 0, 8, 9, 1)
dsb_spawn(44, "mirror", 0, 12, 9, 3)
dsb_spawn(54, "mirror", 0, 15, 9, 1)
dsb_spawn(15, "mirror", 0, 2, 10, 0)
dsb_spawn(23, "mirror", 0, 3, 11, 1)
dsb_spawn(42, "mirror", 0, 10, 11, 0)
dsb_spawn(5, "mirror", 0, 1, 12, 2)
dsb_spawn(59, "mirror", 0, 16, 12, 3)
dsb_spawn(30, "mirror", 0, 5, 13, 0)
dsb_spawn(8, "doorframe", 0, 1, 14, 4)
dsb_spawn(20, "door_wood_swindow", 0, 1, 14, 4)
dsb_disable(20)
dsb_spawn(36, "fakewall", 0, 8, 14, 4)
dsb_spawn(9, "stairsdown", 0, 1, 15, 4)
dsb_spawn(31, "stairsdown", 0, 6, 15, 4)
dsb_spawn(32, "doorframe", 0, 7, 15, 4)
dsb_spawn(33, "door_portcullis", 0, 7, 15, 4)
dsb_spawn(34, "doorbutton", 0, 7, 15, 4)
dsb_spawn(46, "mirror", 0, 12, 15, 0)
dsb_spawn(101, "stairsup", 1, 19, 3, 4)
dsb_spawn(102, "stairsup", 1, 19, 7, 4)
dsb_spawn(98, "rockpile", 1, 16, 8, 0)
mon_hp(98, 253)
dsb_spawn(97, "rockpile", 1, 16, 8, 1)
mon_hp(97, 243)
dsb_spawn(104, "rockpile", 1, 19, 8, 0)
mon_hp(104, 254)
dsb_spawn(103, "rockpile", 1, 19, 8, 1)
mon_hp(103, 244)
dsb_spawn(106, "rockpile", 1, 19, 8, 2)
mon_hp(106, 244)
dsb_spawn(105, "rockpile", 1, 19, 8, 3)
mon_hp(105, 244)
dsb_spawn(100, "rockpile", 1, 18, 9, 4)
mon_hp(100, 249)
dsb_spawn(107, "rockpile", 1, 20, 9, 4)
mon_hp(107, 255)
dsb_spawn(99, "rockpile", 1, 17, 10, 4)
mon_hp(99, 247)
dsb_spawn(73, "mummy", 1, 2, 13, 0)
mon_hp(73, 139)
dsb_spawn(75, "mummy", 1, 2, 13, 2)
mon_hp(75, 135)
dsb_spawn(74, "mummy", 1, 2, 13, 3)
mon_hp(74, 137)
dsb_spawn(77, "mummy", 1, 2, 14, 2)
mon_hp(77, 135)
dsb_spawn(76, "mummy", 1, 2, 14, 3)
mon_hp(76, 138)
dsb_spawn(92, "mummy", 1, 5, 14, 0)
mon_hp(92, 133)
dsb_spawn(91, "mummy", 1, 5, 14, 1)
mon_hp(91, 133)
dsb_spawn(90, "mummy", 1, 5, 14, 2)
mon_hp(90, 136)
dsb_spawn(93, "mummy", 1, 5, 14, 3)
mon_hp(93, 133)
dsb_spawn(72, "stairsup", 1, 1, 15, 4)
dsb_spawn(85, "mummy", 1, 4, 15, 0)
mon_hp(85, 39)
dsb_spawn(84, "mummy", 1, 4, 15, 1)
mon_hp(84, 38)
dsb_spawn(83, "mummy", 1, 4, 15, 2)
mon_hp(83, 38)
dsb_spawn(82, "mummy", 1, 4, 15, 3)
mon_hp(82, 35)
dsb_spawn(96, "stairsup", 1, 6, 15, 4)
dsb_spawn(88, "mummy", 1, 4, 16, 0)
mon_hp(88, 135)
dsb_spawn(87, "mummy", 1, 4, 16, 1)
mon_hp(87, 136)
dsb_spawn(86, "mummy", 1, 4, 16, 2)
mon_hp(86, 134)
dsb_spawn(89, "mummy", 1, 4, 16, 3)
mon_hp(89, 137)
dsb_spawn(95, "mummy", 1, 5, 16, 2)
mon_hp(95, 139)
dsb_spawn(94, "mummy", 1, 5, 16, 3)
mon_hp(94, 134)
dsb_spawn(81, "mummy", 1, 2, 17, 0)
mon_hp(81, 138)
dsb_spawn(80, "mummy", 1, 2, 17, 1)
mon_hp(80, 137)
dsb_spawn(79, "mummy", 1, 2, 17, 2)
mon_hp(79, 138)
dsb_spawn(78, "mummy", 1, 2, 17, 3)
mon_hp(78, 140)
exvar = {
[1] = { msg = 100001,
target = 20,
champion = 1,
delay = 1,
disable_self = true },
[3] = { champion = 3 },
[5] = { msg = 100001,
target = 69,
champion = 2,
delay = 1,
disable_self = true },
[11] = { msg = 100001,
target = 20,
champion = 4,
delay = 1,
disable_self = true },
[15] = { msg = 100001,
target = 20,
champion = 5,
delay = 1,
disable_self = true },
[17] = { champion = 6 },
[21] = { champion = 7 },
[23] = { champion = 10 },
[25] = { msg = 100001,
target = 20,
champion = 8,
delay = 1,
disable_self = true },
[28] = { champion = 9 },
[30] = { champion = 11 },
[33] = { fire_power = 9999 },
[34] = { target = 33 },
[35] = { champion = 12 },
[37] = { text = "THERE IS ONLY ONE LEVEL HERE.                        /FIRST CHOOSE YOUR CHAMPIONS...THEN SAVE THE GAME.../THEN RESTART WITH THE UTILITY DISK." },
[39] = { champion = 13 },
[42] = { champion = 14 },
[44] = { champion = 15 },
[46] = { champion = 16 },
[47] = { champion = 17 },
[49] = { champion = 18 },
[52] = { champion = 19 },
[54] = { champion = 23 },
[59] = { champion = 20 },
[60] = { champion = 21 },
[61] = { champion = 22 },
[63] = { fire_power = 9999 },
[64] = { target = 63 },
[65] = { msg = 100001,
target = 20,
champion = 24,
delay = 1,
disable_self = true },
}
dsb_spawnburst_end()
dsb_set_gameflag(1568)
EDITOR_FLAGS = 255
dsb_party_place(0, 9, 0, 2)

